### ISSUE TITLE
MIG blogs + scenario links

### ISSUE THREAD

**Issue by nanoonan538** [microsoft/ComplianceCxE#10]
[Enter feedback here]

Could we expand how we are pointing to the relevant blog posts (esp. with newer features like multi-stage disposition)? and the scenario based demos?

https://techcommunity.microsoft.com/t5/security-compliance-and-identity/bg-p/MicrosoftSecurityandCompliance/label-name/Microsoft%20Information%20Governance

https://techcommunity.microsoft.com/t5/security-compliance-and-identity/bg-p/MicrosoftSecurityandCompliance/label-name/Microsoft%20Information%20Governance
---
#### Document Details

⚠ *Do not edit this section. It is required for tracking

Page Path: [https://microsoft.github.io/ComplianceCxE/resources/mig/](https://microsoft.github.io/ComplianceCxE/resources/mig/)

**Comment by brenle** [comment]
@nanoonan538 I don't understand the request/question - can you clarify

**Comment by brenle** [comment]
Closing no response
