### ISSUE TITLE
Spelling error in title

### ISSUE THREAD

**Issue by pohanlon1980** [microsoft/ComplianceCxE#11]
[Title of the document has a spelling error..."Adanced..."]

---
#### Document Details

⚠ *Do not edit this section. It is required for tracking

Page Path: [https://microsoft.github.io/ComplianceCxE/dag/aed-audit/](https://microsoft.github.io/ComplianceCxE/dag/aed-audit/)

**Comment by brenle** [comment]
Fixed - thanks for reporting
