### ISSUE TITLE
Link to blog post Lifecycle of an item in SharePoint: Where does it go? broken

### ISSUE THREAD

**Issue by ancmarti** [microsoft/ComplianceCxE#25]
[Link to blog post "Lifecycle of an item in SharePoint: Where does it go?" broken]

---
#### Document Details

⚠ *Do not edit this section. It is required for tracking

Page Path: [https://microsoft.github.io/ComplianceCxE/resources/mig/](https://microsoft.github.io/ComplianceCxE/resources/mig/)

**Comment by brenle** [comment]
removed & added updated blogs
