### ISSUE TITLE
Link to Adaptive Scopes Exchange Workload JumpStart broken

### ISSUE THREAD

**Issue by ancmarti** [microsoft/ComplianceCxE#26]
**The following URL produced a 404 error**: https://microsoft.github.io/ComplianceCxE/playbooks/migjump
**The referring URL was**: https://microsoft.github.io/ComplianceCxE/resources/mig/

[Link to Adaptive Scopes Exchange Workload JumpStart broken]

**Comment by brenle** [comment]
fixed
