### ISSUE TITLE
MIP Deployment Guide

### ISSUE THREAD

**Issue by nanoonan538** [microsoft/ComplianceCxE#6]
[Enter feedback here]
The link to the MIP Deployment Guide results in a 404 error.
https://microsoft.github.io/dag/mip-dlp

---
#### Document Details

⚠ *Do not edit this section. It is required for tracking

Page Path:https://github.com/microsoft/ComplianceCxE/blob/public/docs/resources/mip.html

**Comment by brenle** [comment]
fixed by adding site_url to mkdocs.yml.  relative URLs were broken without as the site is hosted on /ComplianceCxE/
