### ISSUE TITLE
webinar link for MIG

### ISSUE THREAD

**Issue by nanoonan538** [microsoft/ComplianceCxE#9]
[Enter feedback here]
The webinar link for MIG resources results in a 404 error. 

We might also point to some of the videos specific to MIG in the IP&G playlist on the Microsoft Security Youtube channel as having some of the more recent overviews.
https://www.youtube.com/watch?v=onEY3NzEip4&list=PL3ZTgFEc7Lytd2UXVImhZUj30LdsLtmFc

---
#### Document Details

⚠ *Do not edit this section. It is required for tracking

Page Path: [https://microsoft.github.io/ComplianceCxE/resources/mig/](https://microsoft.github.io/ComplianceCxE/resources/mig/)

**Comment by brenle** [comment]
good catch; webinar link was broken for all resources pages. fixed on all of them.

@nanoonan538 - for the video addition, feel free to create a PR with whatever additions/changes you think would be good :)

See [https://microsoft.github.io/ComplianceCxE/how-to-contribute/](https://microsoft.github.io/ComplianceCxE/how-to-contribute/)
